//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patient_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentTbl
    {
        public int Appointment_ID { get; set; }
        public Nullable<int> Doctor_ID { get; set; }
        public Nullable<int> Patient_ID { get; set; }
        public Nullable<int> Dept_ID { get; set; }
        public Nullable<System.DateTime> Apt_Date { get; set; }
        public Nullable<System.TimeSpan> Apt_Time { get; set; }
        public string Description { get; set; }
        public string Email { get; set; }
        public string Diseases { get; set; }
        public Nullable<int> Schedule_ID { get; set; }
    
        public virtual DepartmentTbl DepartmentTbl { get; set; }
        public virtual DoctorTbl DoctorTbl { get; set; }
        public virtual ScheduleTbl ScheduleTbl { get; set; }
        public virtual PatientsTbl PatientsTbl { get; set; }
    }
}
