//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patient_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DoctorTbl()
        {
            this.AppointmentTbls = new HashSet<AppointmentTbl>();
            this.ScheduleTbls = new HashSet<ScheduleTbl>();
            this.PrescriptionTbls = new HashSet<PrescriptionTbl>();
        }
    
        public int Doctor_ID { get; set; }
        public string Dr_FirstName { get; set; }
        public string Dr_LastName { get; set; }
        public string Dr_Email { get; set; }
        public string Dr_Password { get; set; }
        public Nullable<System.DateTime> Dr_DOB { get; set; }
        public string Dr_Gender { get; set; }
        public string Dr_Phone { get; set; }
        public string Dr_Qualification { get; set; }
        public string Dr_Address { get; set; }
        public string Dr_City { get; set; }
        public string Dr_State { get; set; }
        public Nullable<int> Dr_Pincode { get; set; }
        public string Dr_ImagePath { get; set; }
        public string Dr_Status { get; set; }
        public Nullable<int> Dept_ID { get; set; }
        public Nullable<decimal> Fees { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentTbl> AppointmentTbls { get; set; }
        public virtual DepartmentTbl DepartmentTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduleTbl> ScheduleTbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrescriptionTbl> PrescriptionTbls { get; set; }
    }
}
