//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patient_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dr_LoginInfo
    {
        public int Login_Id { get; set; }
        public int Doctor_ID { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> Login_Details { get; set; }
    
        public virtual DoctorTbl DoctorTbl { get; set; }
    }
}
