//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patient_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Patient_Management_SystemEntities : DbContext
    {
        public Patient_Management_SystemEntities()
            : base("name=Patient_Management_SystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminTbl> AdminTbls { get; set; }
        public virtual DbSet<AppointmentTbl> AppointmentTbls { get; set; }
        public virtual DbSet<ContactUsTbl> ContactUsTbls { get; set; }
        public virtual DbSet<DepartmentTbl> DepartmentTbls { get; set; }
        public virtual DbSet<DoctorTbl> DoctorTbls { get; set; }
        public virtual DbSet<LoginInfo> LoginInfoes { get; set; }
        public virtual DbSet<PatientsTbl> PatientsTbls { get; set; }
        public virtual DbSet<ScheduleTbl> ScheduleTbls { get; set; }
        public IEnumerable<object> PaymentTbls { get; internal set; }
    }
}
