//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patient_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentTbl
    {
        public int Payment_ID { get; set; }
        public int Patient_ID { get; set; }
        public decimal Amount { get; set; }
        public string PaymentMethod { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
    
        public virtual PatientsTbl PatientsTbl { get; set; }
    }
}
