//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patient_Management_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginInfo
    {
        public int Login_Id { get; set; }
        public int Patient_Id { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Login_Details { get; set; }
    
        public virtual PatientsTbl PatientsTbl { get; set; }
    }
}
