//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patient_Management_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScheduleTbl()
        {
            this.AppointmentTbls = new HashSet<AppointmentTbl>();
        }
    
        public int Schedule_ID { get; set; }
        public int Doctor_ID { get; set; }
        public int Dept_ID { get; set; }
        public System.TimeSpan Start_Time { get; set; }
        public System.TimeSpan End_Time { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Available_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentTbl> AppointmentTbls { get; set; }
        public virtual DepartmentTbl DepartmentTbl { get; set; }
        public virtual DoctorTbl DoctorTbl { get; set; }
    }
}
